/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
#include "GPIO.h"
#include "Console.h"

int main(void)
{
	MCU_Clock_Setup();
	Delay_Config();
	GPIO_Pin_Setup(GPIOA, 8, ALTERNATE_FUNCTION_OUTPUT_PUSHPULL, TIM1_CH1);
	GPIO_Pin_Setup(GPIOA, 15, INPUT_FLOATING, TIM2_CH1);
	Console_Init(USART1, 9600);

	RCC ->APB2ENR |= RCC_APB2ENR_TIM1EN;
	RCC -> APB1ENR |= RCC_APB1ENR_TIM2EN;
	TIM1->PSC = 1;
	TIM1->ARR = 3-1;
	TIM1 -> CCR1 = 1;
	TIM1->CCMR1 |= TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC1PE;
	TIM1->BDTR |= TIM_BDTR_MOE;
	TIM1->CCER |= TIM_CCER_CC1E;
	TIM1->CR1 |= TIM_CR1_ARPE;
    TIM1->EGR |= TIM_EGR_UG;
	TIM1->CR1 |= TIM_CR1_CEN;


	TIM2 -> PSC = 0;
	TIM2 -> ARR = 0xFFFF;
	TIM2 -> CCMR1 |= TIM_CCMR1_CC1S_0;                  //IC1 mapped to T1
	TIM2 -> CCMR1 |= TIM_CCMR1_CC2S_1;                  //IC2 mapped to T1
	TIM2 -> CCMR1 &= ~TIM_CCMR1_IC1PSC;                 //No division of incoming signal
	TIM2 -> CCMR1 &= ~TIM_CCMR1_IC2PSC;                 //No division of incoming signal
	TIM2 -> SMCR |= TIM_SMCR_TS_2 | TIM_SMCR_TS_0;      //trigger select
	TIM2 -> SMCR |= TIM_SMCR_SMS_2;                     //activate slave mode
	TIM2 -> CCER &= ~TIM_CCER_CC1P;                     //non inverted
	TIM2 -> CCER |= TIM_CCER_CC2P;                      //inverted
	TIM2 -> CCER |= TIM_CCER_CC1E;                      //Enable capture on CCR1
	TIM2 -> CCER |= TIM_CCER_CC2E;                      //Enable capture on CCR2
	TIM2 -> CR1 |= TIM_CR1_CEN;                         //Enable timer


    /* Loop forever */
	for(;;)
	{
		printConsole(USART1, "%d | %d \r\n",TIM2->CCR1,TIM2->CCR2 );

	}
}
